### ISSUE TITLE
Research | Find Project

### ISSUE THREAD

**Issue by Miksel90** [Miksel90/development-platforms#2]
Everyone looks through job sites to see what tools/knowledge companies are looking for at the moment

**Comment by Miksel90** [comment]
This looks fun! JS animation

Greensock!
https://gsap.com/

**Comment by Miksel90** [comment]
Also trying to see if I find anything cool within devops. A lot of companies are asking for that.

**Comment by Miksel90** [comment]
Google cloud platform: 

https://cloud.google.com/

**Comment by Miksel90** [comment]
What About Flutter? Looks kind of fun, and its not written about yet.

**Comment by HansMariusAndreassen** [comment]
Flutter chosen for this case-study
